server.port: 9003

tracer.property: I AM THE DEFAULT
spring.jpa.show-sql: true
spring.datasource.url: jdbc:mysql://localhost:3306/jpa_tutorials
spring.datasource.username: root
spring.datasource.password: null
spring.datasource.testWhileIdle: true
spring.datasource.validationQuery: SELECT 1
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


#------------------------- Eureka Service Discovery config's -------------------------------      
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
