server.port: 8008
tracing.property: I AM API GATEWAY
      
#------------------------- Eureka Service Discovery config's -------------------------------      
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/      