# Server configserver:  port: 8901
# Datasource configspring:  datasource:    url: jdbc:mysql://localhost:3306/login_service    username: root
    password: 
    test-while-idle: TRUE
    validation-query: SELECT 1

# OAuth config
oauth.client.id: my-app
oauth.client.secret: $2a$08$fL7u5xcvsZl78su29x1ti.dxI.9rYO8t0q5wk2ROJ.1cdR53bmaVG
